//
// Copyright (c) 2026 xueyixuan2026
// Distributed under the MIT License (http://opensource.org/licenses/MIT)
//
// Gobot Framework Implementation
//

#include "gobot_framework.h"
#include <fstream>
#include <sstream>
#include <algorithm>
#include <android/log.h>

#define LOG_TAG "GobotFramework"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

namespace gobot {

GobotFramework::GobotFramework()
    : mDataPath(".")
{
    loadBuiltinActions();
}

GobotFramework::~GobotFramework()
{
}

GobotFramework& GobotFramework::getInstance()
{
    static GobotFramework instance;
    return instance;
}

bool GobotFramework::initialize(const std::string& dataPath)
{
    mDataPath = dataPath;
    LOGI("GobotFramework initialized with data path: %s", dataPath.c_str());
    return true;
}

bool GobotFramework::loadActionFile(const std::string& path)
{
    std::ifstream file(path);
    if (!file.is_open()) {
        LOGE("Failed to open action file: %s", path.c_str());
        return false;
    }

    std::string line;
    ActionData currentAction;
    std::string currentBone;
    bool parsingAction = false;

    while (std::getline(file, line)) {
        if (line.empty() || line[0] == '#') continue;

        if (line[0] == '[') {
            if (parsingAction && !currentAction.name.empty()) {
                mActions[currentAction.name] = currentAction;
                currentAction = ActionData();
                currentBone.clear();
            }
            
            size_t end = line.find(']');
            if (end != std::string::npos) {
                currentAction.name = line.substr(1, end - 1);
                parsingAction = true;
            }
        } else if (parsingAction) {
            if (line.find("description:") == 0) {
                currentAction.description = line.substr(12);
            } else if (line.find("duration:") == 0) {
                currentAction.duration = std::stof(line.substr(9));
            } else if (line.find("bone:") == 0) {
                size_t colon = line.find(':');
                size_t dataStart = line.find(':', colon + 1);
                if (dataStart != std::string::npos) {
                    currentBone = line.substr(colon + 1, dataStart - colon - 1);
                }
            } else if (line.find("|") != std::string::npos && !currentBone.empty()) {
                // frame data: time|x|y|z|rx|ry|rz
                std::stringstream ss(line);
                std::string token;
                std::vector<float> values;
                while (std::getline(ss, token, '|')) {
                    values.push_back(std::stof(token));
                }
                if (values.size() >= 7) {
                    float time = values[0];
                    BoneTransform transform;
                    for (int i = 1; i < 7; ++i) {
                        transform.push_back(values[i]);
                    }
                    currentAction.bones[currentBone][time] = transform;
                }
            }
        }
    }

    if (parsingAction && !currentAction.name.empty()) {
        mActions[currentAction.name] = currentAction;
    }

    file.close();
    LOGI("Loaded action file: %s (%zu actions)", path.c_str(), mActions.size());
    return true;
}

bool GobotFramework::saveActionFile(const std::string& path, const ActionData& action)
{
    std::ofstream file(path);
    if (!file.is_open()) {
        LOGE("Failed to write action file: %s", path.c_str());
        return false;
    }

    file << "# Gobot Action File v1.0\n";
    file << "# Generated by Saba MMD Viewer\n\n";

    file << "[" << action.name << "]\n";
    file << "description:" << action.description << "\n";
    file << "duration:" << action.duration << "\n\n";

    for (const auto& [boneName, frames] : action.bones) {
        file << "bone:" << boneName << ":\n";
        for (const auto& [time, transform] : frames) {
            file << time;
            for (float v : transform) {
                file << "|" << v;
            }
            file << "\n";
        }
        file << "\n";
    }

    file.close();
    LOGI("Saved action file: %s", path.c_str());
    return true;
}

ActionData* GobotFramework::getAction(const std::string& name)
{
    auto it = mActions.find(name);
    if (it != mActions.end()) {
        return &it->second;
    }
    return nullptr;
}

std::vector<std::string> GobotFramework::getActionNames() const
{
    std::vector<std::string> names;
    for (const auto& [name, _] : mActions) {
        names.push_back(name);
    }
    return names;
}

bool GobotFramework::loadSceneFile(const std::string& path)
{
    // JSON-based scene file loading
    std::ifstream file(path);
    if (!file.is_open()) {
        LOGE("Failed to open scene file: %s", path.c_str());
        return false;
    }

    LOGI("Scene file loaded: %s", path.c_str());
    file.close();
    return true;
}

bool GobotFramework::saveSceneFile(const std::string& path, const SceneData& scene)
{
    std::ofstream file(path);
    if (!file.is_open()) {
        return false;
    }
    file.close();
    return true;
}

SceneData* GobotFramework::getScene(const std::string& name)
{
    auto it = mScenes.find(name);
    if (it != mScenes.end()) {
        return &it->second;
    }
    return nullptr;
}

std::vector<std::string> GobotFramework::getSceneNames() const
{
    std::vector<std::string> names;
    for (const auto& [name, _] : mScenes) {
        names.push_back(name);
    }
    return names;
}

bool GobotFramework::loadProject(const std::string& path)
{
    std::ifstream file(path);
    if (!file.is_open()) {
        return false;
    }
    file.close();
    return true;
}

bool GobotFramework::saveProject(const std::string& path, const ProjectData& project)
{
    std::ofstream file(path);
    if (!file.is_open()) {
        return false;
    }
    file.close();
    return true;
}

bool GobotFramework::executeAction(const std::string& name, float time,
                                    std::function<void(const std::string&, const BoneTransform&)> applyBone)
{
    auto* action = getAction(name);
    if (!action) {
        return false;
    }

    float duration = action->duration;
    float normalizedTime = time / duration;
    if (normalizedTime > 1.0f) normalizedTime = 1.0f;

    for (const auto& [boneName, frames] : action->bones) {
        // Find surrounding keyframes and interpolate
        auto it = frames.lower_bound(normalizedTime * duration);
        if (it == frames.end()) {
            if (!frames.empty()) {
                applyBone(boneName, std::prev(it)->second);
            }
        } else if (it == frames.begin()) {
            applyBone(boneName, it->second);
        } else {
            auto prev = std::prev(it);
            float t1 = prev->first;
            float t2 = it->first;
            float t = (normalizedTime * duration - t1) / (t2 - t1);

            const auto& v1 = prev->second;
            const auto& v2 = it->second;
            BoneTransform interpolated;
            for (size_t i = 0; i < std::min(v1.size(), v2.size()); ++i) {
                interpolated.push_back(v1[i] + (v2[i] - v1[i]) * t);
            }
            applyBone(boneName, interpolated);
        }
    }

    return true;
}

bool GobotFramework::applyScene(const std::string& name)
{
    return getScene(name) != nullptr;
}

void GobotFramework::loadBuiltinActions()
{
    // Jump action
    ActionData jump;
    jump.name = "jump";
    jump.description = "Jump animation";
    jump.duration = 0.5f;
    
    KeyFrameMap leftLeg;
    leftLeg[0.0f] = {0,0,0,0,0,0};
    leftLeg[0.15f] = {0,0,0,-0.8f,0,0};
    leftLeg[0.25f] = {0,0,0,0.2f,0,0};
    leftLeg[0.5f] = {0,0,0,0,0,0};
    jump.bones["左足"] = leftLeg;
    
    KeyFrameMap rightLeg;
    rightLeg[0.0f] = {0,0,0,0,0,0};
    rightLeg[0.15f] = {0,0,0,0.8f,0,0};
    rightLeg[0.25f] = {0,0,0,-0.2f,0,0};
    rightLeg[0.5f] = {0,0,0,0,0,0};
    jump.bones["右足"] = rightLeg;
    
    KeyFrameMap center;
    center[0.0f] = {0,0,0,0,0,0};
    center[0.1f] = {0,-2,0,0,0,0};
    center[0.25f] = {0,8,0,0,0,0};
    center[0.4f] = {0,0,0,0,0,0};
    center[0.5f] = {0,0,0,0,0,0};
    jump.bones["センター"] = center;
    
    mActions["jump"] = jump;
    
    // Walk action
    ActionData walk;
    walk.name = "walk";
    walk.description = "Walk animation";
    walk.duration = 1.0f;
    
    auto createWalkCycle = [](const std::vector<float>& times, float amplitude) -> KeyFrameMap {
        KeyFrameMap frames;
        for (size_t i = 0; i < times.size(); ++i) {
            float phase = 3.14159f * 2.0f * times[i] / 1.0f;
            float value = amplitude * std::sin(phase);
            frames[times[i]] = {0, 0, 0, value, 0, 0};
        }
        return frames;
    };
    
    std::vector<float> walkTimes = {0.0f, 0.25f, 0.5f, 0.75f, 1.0f};
    walk.bones["左腕"] = createWalkCycle(walkTimes, -0.3f);
    walk.bones["右腕"] = createWalkCycle(walkTimes, 0.3f);
    walk.bones["左足"] = createWalkCycle(walkTimes, -0.3f);
    walk.bones["右足"] = createWalkCycle(walkTimes, 0.3f);
    
    mActions["walk"] = walk;
    
    // Run action
    ActionData run;
    run.name = "run";
    run.description = "Run animation";
    run.duration = 0.5f;
    
    std::vector<float> runTimes = {0.0f, 0.125f, 0.25f, 0.375f, 0.5f};
    run.bones["左腕"] = createWalkCycle(runTimes, -0.6f);
    run.bones["右腕"] = createWalkCycle(runTimes, 0.6f);
    run.bones["左足"] = createWalkCycle(runTimes, -0.6f);
    run.bones["右足"] = createWalkCycle(runTimes, 0.6f);
    
    mActions["run"] = run;
    
    LOGI("Loaded %zu builtin actions", mActions.size());
}

} // namespace gobot